{{- range $k, $v := $.Values.policies }}
---
apiVersion: netbird.io/v1
kind: NBPolicy
metadata:
  annotations:
    helm.sh/resource-policy: keep
  finalizers:
    - netbird.io/cleanup
  labels:
    app.kubernetes.io/component: operator
    {{- include "netbird-operator-config.labels" $ | nindent 4 }}
  name: {{ $k }}
spec:
  name: {{ $v.name }}
  sourceGroups:
  {{ toYaml $v.sourceGroups | nindent 4}}
  {{- if $v.description }}
  description: {{ $v.description }}
  {{- end }}
  {{- if $v.protocols }}
  protocols: {{ $v.protocols }}
  {{- end }}
  {{- if $v.ports }}
  ports: {{ $v.ports }}
  {{- end }}
  {{- if hasKey $v "bidirectional" }}
  bidirectional: {{ $v.bidirectional }}
  {{- end }}
{{- end }}