{{- if and .Values.authProxy.enabled .Values.authProxy.setupKey (not .Values.authProxy.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-operator.fullname" . }}-auth-proxy-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
type: Opaque
data:
  NB_SETUP_KEY: {{ .Values.authProxy.setupKey | b64enc | quote }}
{{- end }}

