{{- if .Values.authProxy.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-operator.authProxyServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
  {{- with .Values.authProxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-operator.fullname" . }}-auth-proxy
  labels:
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["users", "groups", "serviceaccounts"]
    verbs: ["impersonate"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["userextras/scopes"]
    verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-operator.fullname" . }}-auth-proxy
  labels:
    {{- include "kubernetes-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubernetes-operator.authProxyServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubernetes-operator.fullname" . }}-auth-proxy
  apiGroup: rbac.authorization.k8s.io
{{- end }}

