{{- range $k, $v := $.Values.ingress.policies }}
---
apiVersion: netbird.io/v1
kind: NBPolicy
metadata:
  finalizers:
    - netbird.io/cleanup
  labels:
    app.kubernetes.io/component: operator
    {{- include "kubernetes-operator.labels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
  name: {{ $k }}
spec:
  name: {{ $v.name }}
  sourceGroups:
  {{ toYaml $v.sourceGroups | nindent 4}}
  {{- if $v.description }}
  description: {{ $v.description }}
  {{- end }}
  {{- if $v.protocols }}
  protocols:
  {{ toYaml $v.protocols | nindent 4}}
  {{- end }}
  {{- if $v.ports }}
  ports:
  {{ toYaml $v.ports | nindent 4}}
  {{- end }}
  {{- if hasKey $v "bidirectional" }}
  bidirectional: {{ $v.bidirectional }}
  {{- end }}
{{- end }}